version: "2.4"
services:
  simbotic-openpose:
    tty: true
    stdin_open: true
    runtime: nvidia
    container_name: simbotic-openpose
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID
        - GROUP_ID
      network: host
    devices:
      - "/dev/video0:/dev/video0"
    image: simbotic-openpose/python3:v0.0.1
    environment:
      - DISPLAY
    privileged: true
    cap_add:
      - SYS_PTRACE
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ${CURRENT_DIRECTORY}/videos/
        target: /videos
      - type: bind
        source: ${CURRENT_DIRECTORY}/data/
        target: /data
      - type: bind
        source: ./openpose/
        target: /home/sim/openpose
